"""users table

Revision ID: 9cb238d98dad
Revises: 53aa7a5a54c4
Create Date: 2021-05-20 12:48:19.360804

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '9cb238d98dad'
down_revision = '53aa7a5a54c4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('creation_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.alter_column('messages', 'receiver',
               existing_type=mysql.VARCHAR(length=50),
               nullable=False)
    op.alter_column('messages', 'date',
               existing_type=sa.DATE(),
               nullable=False)
    op.alter_column('messages', 'text',
               existing_type=mysql.VARCHAR(length=160),
               nullable=False)
    op.alter_column('messages', 'sender',
               existing_type=mysql.VARCHAR(length=50),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('messages', 'sender',
               existing_type=mysql.VARCHAR(length=50),
               nullable=True)
    op.alter_column('messages', 'text',
               existing_type=mysql.VARCHAR(length=160),
               nullable=True)
    op.alter_column('messages', 'date',
               existing_type=sa.DATE(),
               nullable=True)
    op.alter_column('messages', 'receiver',
               existing_type=mysql.VARCHAR(length=50),
               nullable=True)
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
